services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432" # TODO: Should not expose and should be in the .env
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ** Add volume for case if db goes down **